### ISSUE TITLE
can't install dsapp on SLES 12

### ISSUE THREAD

**Issue by mfaust78** [snielson/dsapp_python#28]
Was testing the 14.2.1 Beta and wanted to install dsapp on my SLES 12 SP1. Unfortunately it didn't work:

rpm -ivh dsapp-2.00-238.noarch.rpm
error: Failed dependencies:
        libpython2.6.so.1.0()(64bit) is needed by dsapp-2.00-238.noarch
        librpm-4.4.so()(64bit) is needed by dsapp-2.00-238.noarch
        librpmbuild-4.4.so()(64bit) is needed by dsapp-2.00-238.noarch
        librpmdb-4.4.so()(64bit) is needed by dsapp-2.00-238.noarch
        librpmio-4.4.so()(64bit) is needed by dsapp-2.00-238.noarch

uname -a
Linux xxx 3.12.59-60.45-xen #1 SMP Sat Jun 25 06:19:03 UTC 2016 (396c69d) x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp1"

**Comment by snielson** [comment]
I attempted to install GMS 14.2.1 on SLES 12 a while back.. didn't go well.
I'll have to try again, now that it seems more stable, and work with dsapp to make sure all needed modules / libraries are included.

**Comment by snielson** [comment]
Would you be willing to test this version of dsapp on your SLES 12 GMS beta?
ftp://107.188.136.7/public/dsapp-238v3.zip

I was able to install dsapp, but not entirely test... due to postgresql issues.

**Comment by mfaust78** [comment]
Sure. Did so. Install worked on SLES 12 SP1 GMS 14.2.1-200.
Running by just "dsapp" does not work:
-> python: can't open file '/opt/novell/datasync/tools/dsapp/dsapp.pyc': [Errno 2] No such file or directory
starting it with "python /opt/novell/datasync/tools/dsapp/dsapp.py" works fine.

Health-Check looks ok with thes exceptions:
- "Database Maintenance" can't find any vaccum date.
- "RPM Check" -> Missing rpm: pyxml
no clue what replaced pyxml GMS for SLES 12

Other than that I didn't see anything not working.

**Comment by snielson** [comment]
I was running into "Bad Magic Number" errors, as dsapp was compiled on python 2.6 and SLES 12 uses python 2.7.

Because of that, I left everything uncompiled (you'll notice you can now view and edit all the .py files if you'd like)

Because of that, I had to replace the /usr/local/bin/dsapp
Maybe updating to this rpm didn't remove the old one? try a full rpm -e dsapp and reinstall the new one.

For the Database Maintenance, that is normal with a new GMS database - Don't know how to say warning rather than failed if they are blank (without checking the install dates of GMS itself)

RPM check.. I'll need to do some more research too. I'm setting up a new dedicated SLES 12 server to continue building and testing dsapp

**Comment by snielson** [comment]
Tested dsapp v239 on SLES 12 - believe most issues for SLES 12 have been resolved.  Closing issue
